services:
  app:
    image: zone117x/node-open-mining-portal:latest
    container_name: bch_stratum_pool
    restart: on-failure
    ports:
      - "3032:3032"
      - "8082:8082"
    environment:
      - NODE_ENV=production
