services:
  app_proxy:
    image: getumbrel/app-proxy:v0.1.1
    environment:
      APP_HOST: bch-node_app_1
      APP_PORT: 8332

  app:
    image: bitcoincashnode/bitcoin-cash-node:27.1.0
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/app-data:/data
    ports:
      - "8333:8333"
    command:
      - -datadir=/data
      - -server=1
      - -txindex=1
      - -rpcuser=trockel_bch_user
      - -rpcpassword=sua_senha_secreta_rpc
      - -rpcallowip=0.0.0.0/0
      - -rpcbind=0.0.0.0
