services:
  app_proxy:
    image: getumbrel/app-proxy:v0.1.1
    environment:
      APP_HOST: trockel-bch-pool_app_1
      APP_PORT: 8082

  app:
    image: zone117x/node-open-mining-portal:latest
    container_name: trockel-bch-pool_app_1
    restart: on-failure
    ports:
      - "3032:3032"
    volumes:
      - ${APP_DATA_DIR}/data/app-data:/config
    environment:
      - NODE_ENV=production
