services:
  app_proxy:
    image: getumbrel/app-proxy:v0.1.1
    environment:
      APP_HOST: trockel-bch-node_app_1
      APP_PORT: 18332

  app:
    image: zquestz/bitcoin-cash-node:27.1.0
    container_name: trockel-bch-node_app_1
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
    command:
      - -datadir=/data
      - -server=1
      - -txindex=1
      - -port=18333
      - -rpcport=18332
      - -rpcuser=trockel_bch_user
      - -rpcpassword=sua_senha_secreta_rpc
      - -rpcallowip=0.0.0.0/0
      - -rpcbind=0.0.0.0
